spring:
  profiles:
    active: clustering
tmc:
  auth:
    tokenUrl: ${TMC_AUTH_URL} # SHOULD BE STORED IN YOUR ENVIRONMENT
    clientId: ${TMC_CLIENT_ID} # SHOULD BE STORED IN YOUR ENVIRONMENT
    clientSecret: ${TMC_CLIENT_SECRET} # SHOULD BE STORED IN YOUR ENVIRONMENT
  feed-consumer:
    streamUrl: ${TMC_FEED_URL}  # SHOULD BE STORED IN YOUR ENVIRONMENT
    flow: ${TMC_FLOW} # SHOULD BE STORED IN YOUR ENVIRONMENT
    hoursOfHistory: 1
logging:
  level:
    com.autonomic.ext: INFO

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info,metric"
        exclude: "env,beans"
